<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Try it for Free</name>
   <tag></tag>
   <elementGuidId>7b939596-3318-4418-bb8a-b8536dfee49a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='linkadd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#linkadd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fc37421-7ff0-4b60-8ea1-2c21fb5cc03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>311e9240-78b5-48a9-a331-258921e28b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-ohrm btn-tryit-free</value>
      <webElementGuid>f733ddeb-24b2-44b4-90aa-b3551fa79ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkadd</value>
      <webElementGuid>ccc68a43-a24f-4759-89ea-2a56070f8bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>buttonClick()</value>
      <webElementGuid>d7c7b536-283f-4771-b2b4-bc8be2cd8ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Try it for Free</value>
      <webElementGuid>8aa14201-0058-484c-a840-d159b6543d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkadd&quot;)</value>
      <webElementGuid>a79e0f7a-9e4b-4b9e-b9bf-bf2b97f22a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='linkadd']</value>
      <webElementGuid>e5bc53bc-18b0-4164-9700-79665079e69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peace of mind is just a few clicks away!'])[1]/following::button[1]</value>
      <webElementGuid>045b2460-1e2a-40fd-955e-86af17b5d153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[2]/following::button[1]</value>
      <webElementGuid>85e45c95-cebb-4462-9135-2e1897c499b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have 5 million + active users worldwide'])[1]/preceding::button[1]</value>
      <webElementGuid>aef18724-c1cd-4fb0-8d6b-403a4f8e0955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR for All'])[3]/preceding::button[1]</value>
      <webElementGuid>1e063b34-d0bc-415e-bb80-1d7a43583867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Try it for Free']/parent::*</value>
      <webElementGuid>a3c43a24-8c3c-465b-a0c1-51d45e9b1bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>b4b22125-6d1e-454a-95a6-b057401b2d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'linkadd' and (text() = 'Try it for Free' or . = 'Try it for Free')]</value>
      <webElementGuid>d0f0d649-9aca-46e1-9282-bdbd13d3c36f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
